# Generated by Django 2.0.2 on 2018-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=100)),
                ('last_name', models.TextField()),
                ('img', models.ImageField(upload_to='images/employee')),
                ('website', models.URLField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(null=True)),
                ('skills', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
