# Generated by Django 2.0.2 on 2018-07-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekzarta', '0002_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='city',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
